[package]
name = "rusty_rogue"
version = "0.1.0"
authors = ["Andy Barron <AndrewLBarron@gmail.com>"]
edition = '2018'

[dependencies]
num = "0.2.1"
rand = "0.7.3"
num_cpus = "1.13.0"
nalgebra = "0.21.0"
rustc-serialize = "0.3.24"
petgraph = "0.5.1"
sfml = "0.15.1"
